project:
  type: book
  output-dir: docs

book:
  title: "Answers to selected exercises"
  author: "John Maindonald"
  date: "2024-03-15"
  chapters:
    - index.qmd
    - ch1.qmd
    - ch2.qmd
    - ch3.qmd
    - ch4.qmd
    - ch5.qmd
    - ch6.qmd
    - ch7.qmd
    - ch8.qmd
    - ch9.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    toc: true
    page-layout: full
  pdf:
    documentclass: scrreprt
    toc: true
    



