<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.4.549">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="dcterms.date" content="2024-03-15">

<title>Answers to selected exercises - 8&nbsp; Answers to Selected Chapter 8 Exercises</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./ch9.html" rel="next">
<link href="./ch7.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./ch8.html"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Answers to Selected Chapter 8 Exercises</span></a></li></ol></nav>
        <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-full">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Answers to selected exercises</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ch1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Answers to Selected Chapter 1 Exercises</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ch2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Answers to Selected Chapter 2 Exercises</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ch3.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Answers to Selected Chapter 3 Exercises</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ch4.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Answers to Selected Chapter 4 Exercises</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ch5.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Answers to Selected Chapter 5 Exercises</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ch6.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Answers to Selected Chapter 6 Exercises</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ch7.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Answers to Selected Chapter 7 Exercises</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ch8.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Answers to Selected Chapter 8 Exercises</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ch9.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Answers to Selected Chapter 9 Exercises</span></span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar zindex-bottom">
        
    </div>
<!-- main -->
<main class="content column-page-right" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Answers to Selected Chapter 8 Exercises</span></h1>
<p class="subtitle lead">Tree-based Classification and Regression</p>
</div>



<div class="quarto-title-meta column-page-right">

    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">March 15, 2024</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<div class="cell">
<style type="text/css">
.colbox {
  padding: 1em;
  background: white;
  color: black;
  border: 2px solid orange;
  border-radius: 10px;
}
.center {
  text-align: left;
}
}
</style>
</div>
<div class="cell" data-layout-align="center" data-quiet="true">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(DAAG)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(rpart)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="colbox">
<div data-latex="">
<p>Exercise 1</p>
</div>
<p>Refer to the <code>DAAG::headInjury</code> data frame.</p>
<ol type="a">
<li><p>Use the default setting in <code>rpart()</code> to obtain a tree-based model for predicting occurrence of clinically important brain injury, given the other variables.</p></li>
<li><p>How many splits gives the minimum cross-validation error?</p></li>
<li><p>Prune the tree using the 1 standard error rule.</p></li>
</ol>
</div>
<ol type="a">
<li></li>
</ol>
<div class="cell" data-layout-align="center" data-ou.width="50%">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">29</span>)         <span class="do">## Gives the results presented here</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>injury.rpart <span class="ot">&lt;-</span> <span class="fu">rpart</span>(clinically.important.brain.injury <span class="sc">~</span> ., </span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>                      <span class="at">data=</span>headInjury, <span class="at">method=</span><span class="st">"class"</span>, <span class="at">cp=</span><span class="fl">0.0001</span>)</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a><span class="fu">plotcp</span>(injury.rpart)</span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a><span class="fu">printcp</span>(injury.rpart)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Classification tree:
rpart(formula = clinically.important.brain.injury ~ ., data = headInjury, 
    method = "class", cp = 1e-04)

Variables actually used in tree construction:
[1] age.65                amnesia.before        basal.skull.fracture 
[4] GCS.13                GCS.15.2hours         high.risk            
[7] loss.of.consciousness vomiting             

Root node error: 250/3121 = 0.080103

n= 3121 

      CP nsplit rel error xerror     xstd
1 0.0400      0     1.000  1.000 0.060660
2 0.0360      2     0.920  1.008 0.060881
3 0.0140      3     0.884  0.940 0.058965
4 0.0080      5     0.856  0.932 0.058734
5 0.0001     10     0.816  0.924 0.058502</code></pre>
</div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="ch8_files/figure-html/ex1a-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
</div>
<p>The setting <code>cp=0.0001</code> was reached after some experimentation.</p>
<ol start="2" type="a">
<li><p>The minimum cross-validated relative error is for <code>nsplit=3</code>, i.e., for a tree size of 4.</p></li>
<li><p>The one-standard-error rule likewise chooses <code>nsplit=3</code>, with <code>cp=0.014</code>. Setting <code>cp=0.02</code>, i.e., larger than <code>cp</code> for the next smallest number of splits, will prune the tree back to this size. We have</p></li>
</ol>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>injury0.rpart <span class="ot">&lt;-</span> <span class="fu">prune</span>(injury.rpart, <span class="at">cp=</span><span class="fl">0.02</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>We plot the tree from (a) that shows the cross-validated relative error, and the tree obtained from (c).</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="ch8_files/figure-html/unnamed-chunk-3-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%"></p>
</figure>
</div>
</div>
</div>
<p>Plots are from the <code>rpart</code> analysis of the head injury data: (i) cross-validated relative error versus <code>cp</code>; and (ii) the tree obtained in (c).</p>
<p>There can be substantial change from one run to the next.</p>
<div class="colbox">
<div data-latex="">
<p>Exercise 2</p>
</div>
<p>The data set <code>mifem</code> is part of the larger data set in the data frame <code>monica</code> that we have included in our <em>DAAG</em> package. Use tree-based regression to predict mortality in this larger data set. What is the most immediately striking feature of your analysis? Should this be a surprise?</p>
</div>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>monica.rpart <span class="ot">&lt;-</span> <span class="fu">rpart</span>(outcome <span class="sc">~</span> ., <span class="at">data=</span>monica, <span class="at">method=</span><span class="st">"class"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(monica.rpart)</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a><span class="fu">text</span>(monica.rpart)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="ch8_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%"></p>
</figure>
</div>
</div>
</div>
<p>Those who were not hospitalized were very likely to be dead! Check by examining the table:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(monica<span class="sc">$</span>hosp, monica<span class="sc">$</span>outcome)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   
    live dead
  y 3522  920
  n    3 1922</code></pre>
</div>
</div>
<div class="colbox">
<div data-latex="">
<p>Exercise 3</p>
</div>
<blockquote class="blockquote">
<p><strong>Note:</strong> The second sentence of the exercise in the published text is a mistake. There is no multiple regression example with this dataset in Chapter 3, or for that matter elsewhere in the text. What follows is a replacement for the existing exercise.</p>
</blockquote>
<p>Use <code>qqnorm()</code> to check differences from normality in <code>nsw74psid1::re78</code>. What do&nbsp;you notice? Use tree-based regression to predict <code>re78</code>, and check differences from normality in the distribution of residuals.<br>
What do&nbsp;you notice about the tails of the distribution?</p>
<ol type="a">
<li><p>Use the function <code>car::powerTransform()</code> with <code>family='bcnPower'</code> to search for a transformation that will bring the distribution of <code>re78</code> closer to normality. Run summary on the output to get values (suitably rounded values are usually preferred) of <code>lambda</code> and <code>gamma</code> that you can then supply as arguments to <code>car::bcnPower()</code> to obtain transformed values <code>tran78</code> of <code>re78</code>. Use <code>qqnorm()</code> with the transformed data to compare its distribution with a normal distribution. The distribution should now be much closer to normal, making the choice of splits that maximize the between-groups sum-of-squares sums of squares about the mean a more optimal procedure.</p></li>
<li><p>Use tree-based regression to predict <code>tran78</code>, and check differences from normality in the distribution of residuals. What do&nbsp;you now notice about the tails of the distribution? What are the variable importance ranks i) if the tree is chosen that gives the minimum cross-validated error; ii) if the tree is chosen following the one standard error criterion? In each case, calculate the cross-validated relative error.</p></li>
<li><p>Do a random forest fit to the transformed data, and compare the bootstrap error with then cross-validated error from the <code>rpart</code> fits.</p></li>
</ol>
</div>
<p>In order to reproduce the same results as given here, do:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">41</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Code is:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>re78.rpart <span class="ot">&lt;-</span> <span class="fu">rpart</span>(re78<span class="sc">~</span>., <span class="at">data=</span>DAAG<span class="sc">::</span>nsw74psid1, <span class="at">cp=</span><span class="fl">0.001</span>)</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plotcp</span>(re78.rpart)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="ch8_files/figure-html/ex3-initial-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
</div>
<p>It is obvious that <code>cp=0.0025</code> will be adequate. At this point, the following is a matter of convenience, to reduce the printed output:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>re78.rpart2 <span class="ot">&lt;-</span> <span class="fu">prune</span>(re78.rpart, <span class="at">cp=</span><span class="fl">0.0025</span>)</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a><span class="fu">printcp</span>(re78.rpart2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Regression tree:
rpart(formula = re78 ~ ., data = DAAG::nsw74psid1, cp = 0.001)

Variables actually used in tree construction:
[1] age  educ re74 re75

Root node error: 6.5346e+11/2675 = 244284318

n= 2675 

          CP nsplit rel error  xerror     xstd
1  0.3446296      0   1.00000 1.00035 0.046300
2  0.1100855      1   0.65537 0.66341 0.039166
3  0.0409403      2   0.54528 0.55609 0.033163
4  0.0317768      3   0.50434 0.51768 0.034633
5  0.0158188      4   0.47257 0.50415 0.035776
6  0.0105727      5   0.45675 0.48920 0.035591
7  0.0105337      6   0.44618 0.48465 0.035586
8  0.0063341      7   0.43564 0.47149 0.034168
9  0.0056603      8   0.42931 0.47158 0.034334
10 0.0038839      9   0.42365 0.46988 0.034652
11 0.0035516     10   0.41976 0.47717 0.035253
12 0.0031768     11   0.41621 0.48009 0.035351
13 0.0028300     12   0.41304 0.48099 0.035472
14 0.0027221     13   0.41021 0.47965 0.035585
15 0.0025000     15   0.40476 0.47885 0.035494</code></pre>
</div>
</div>
<p>To minimize the cross-validated relative error, prune back to 9 splits. Thus e.g., set <code>cp=0.0038</code>.</p>
<p>We could prune before comparing the distribution of residuals to that for a normal distribution. However, that would make little difference to the pattern that we now see. Interested readers may care to check.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>res <span class="ot">&lt;-</span> <span class="fu">resid</span>(re78.rpart2)</span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a><span class="fu">qqnorm</span>(res)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="ch8_files/figure-html/check-resids-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
</div>
<p>The distribution of residuals is highly log-tailed, at both ends of the distribution. This makes the standard deviation an unsatisfactory measure of variation.</p>
<ol type="a">
<li>The <code>car::bcnPower</code> transformation can be used for an initial transformation of <code>re78</code> that provides a better starting point for the tree-based regression.</li>
</ol>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">41</span>)</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>p2 <span class="ot">&lt;-</span> car<span class="sc">::</span><span class="fu">powerTransform</span>(nsw74psid1<span class="sc">$</span>re78, <span class="at">family=</span><span class="st">'bcnPower'</span>) </span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(p2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>bcnPower transformation to Normality 

Estimated power, lambda
                Est Power Rounded Pwr Wald Lwr Bnd Wald Upr Bnd
nsw74psid1$re78    0.3436        0.33       0.2848       0.4025

Estimated location, gamma
                Est gamma Std Err. Wald Lower Bound Wald Upper Bound
nsw74psid1$re78  10604.01 708.1302         9216.072         11991.94

Likelihood ratio tests about transformation parameters
                            LRT df pval
LR test, lambda = (0)  89.16407  1    0
LR test, lambda = (1) 840.46368  1    0</code></pre>
</div>
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>tran78 <span class="ot">&lt;-</span> car<span class="sc">::</span><span class="fu">bcnPower</span>(nsw74psid1<span class="sc">$</span>re78, <span class="at">lambda=</span><span class="fl">0.33</span>, <span class="at">gamma=</span><span class="dv">8000</span>)</span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>tran78a.rpart <span class="ot">&lt;-</span> <span class="fu">rpart</span>(tran78<span class="sc">~</span>., <span class="at">data=</span>DAAG<span class="sc">::</span>nsw74psid1[,<span class="sc">-</span><span class="dv">10</span>], <span class="at">cp=</span><span class="fl">0.002</span>)</span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a><span class="fu">printcp</span>(tran78a.rpart)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Regression tree:
rpart(formula = tran78 ~ ., data = DAAG::nsw74psid1[, -10], cp = 0.002)

Variables actually used in tree construction:
[1] age  educ re74 re75 trt 

Root node error: 925054/2675 = 345.81

n= 2675 

          CP nsplit rel error  xerror     xstd
1  0.3920121      0   1.00000 1.00037 0.024990
2  0.0775515      1   0.60799 0.60884 0.021418
3  0.0426766      2   0.53044 0.54006 0.020860
4  0.0200850      3   0.48776 0.51036 0.021665
5  0.0135415      4   0.46767 0.48870 0.021479
6  0.0069401      5   0.45413 0.47877 0.021806
7  0.0064537      6   0.44719 0.47545 0.022075
8  0.0046938      7   0.44074 0.46694 0.021907
9  0.0042900      8   0.43605 0.46489 0.021950
10 0.0040279      9   0.43176 0.46791 0.022266
11 0.0035599     10   0.42773 0.46378 0.022205
12 0.0032532     11   0.42417 0.46330 0.022355
13 0.0032107     12   0.42091 0.46416 0.022667
14 0.0030128     13   0.41770 0.46360 0.022646
15 0.0025576     14   0.41469 0.46184 0.022609
16 0.0024921     16   0.40958 0.45664 0.022579
17 0.0024719     17   0.40708 0.45811 0.022680
18 0.0024622     18   0.40461 0.45811 0.022680
19 0.0024387     19   0.40215 0.45792 0.022685
20 0.0023563     20   0.39971 0.45792 0.022699
21 0.0021091     21   0.39735 0.45478 0.022676
22 0.0020508     22   0.39525 0.45630 0.022656
23 0.0020102     23   0.39319 0.45630 0.022656
24 0.0020000     24   0.39118 0.45546 0.022646</code></pre>
</div>
</div>
<p>The minimum cross-validated relative error is at <code>nsplit=21</code>. The one standard error limit is 0.477 (=0.45478 +0.022676, round to 3 d.p.). The one standard error rule suggests taking <code>nsplit=6</code>.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>tran78se.rpart <span class="ot">&lt;-</span> <span class="fu">prune</span>(tran78a.rpart, <span class="at">cp=</span><span class="fl">0.0065</span>)   <span class="do">## 1 SE rule</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>tran78.rpart <span class="ot">&lt;-</span> <span class="fu">prune</span>(tran78a.rpart, <span class="at">cp=</span><span class="fl">0.0021</span>)     <span class="do">## Min xval rel error</span></span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>res <span class="ot">&lt;-</span> <span class="fu">resid</span>(tran78se.rpart)</span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a><span class="fu">qqnorm</span>(res)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="ch8_files/figure-html/prune-6-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
</div>
<p>The long tails have now gone.</p>
<p>Note that the root node error is given as 192.99. The cross-validated errors for the two trees are, rounded to one decimal place:</p>
<ul>
<li>One SE rule: <code>round(192.99*.46697,1) = 90.1</code></li>
<li>Minimum cross-validated error: <code>round(192.99*0.45739,1) = 88.3</code></li>
</ul>
<ol start="3" type="a">
<li></li>
</ol>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(randomForest)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>randomForest 4.7-1.1</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Type rfNews() to see new features/changes/bug fixes.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>tran78.rf <span class="ot">&lt;-</span> <span class="fu">randomForest</span>(<span class="at">y=</span>tran78, <span class="at">x=</span>DAAG<span class="sc">::</span>nsw74psid1[,<span class="sc">-</span><span class="dv">10</span>])</span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>tran78.rf</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
 randomForest(x = DAAG::nsw74psid1[, -10], y = tran78) 
               Type of random forest: regression
                     Number of trees: 500
No. of variables tried at each split: 3

          Mean of squared residuals: 140.2498
                    % Var explained: 59.44</code></pre>
</div>
</div>
<p>The mean of the squared residuals is given as 140.2498427. This is substantially larger than either of the cross-validated errors that are given above from the tree created using <code>rpart()</code>. With only a small number of variables used in tree construction, ::: {.colbox data-latex=““} ::: {data-latex=”“} Exercise 4 ::: The complete email spam dataset is available from https://archive.ics.uci.edu/dataset/94/spambase or from the <em>bayesreg</em> package. Carry out a tree-based regression using all 57 available explanatory variables. Determine the change in the cross-validation estimate of predictive accuracy. ::: We set the random number seed to 21, to allow users to reproduce our results. In most other contexts, it will be best not to set a seed.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(<span class="st">'spambase'</span>, <span class="at">package=</span><span class="st">'bayesreg'</span>)</span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a><span class="do">## For ease of labeling output, specify short names.  </span></span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a><span class="do">## Use the following, or do, e.g., nam &lt;- c(paste0('v',1:57), 'yesno')</span></span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a>nam <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"make"</span>, <span class="st">"address"</span>, <span class="st">"all"</span>, <span class="st">"threeD"</span>, <span class="st">"our"</span>, <span class="st">"over"</span>, <span class="st">"remove"</span>, </span>
<span id="cb24-5"><a href="#cb24-5" aria-hidden="true" tabindex="-1"></a><span class="st">"internet"</span>, <span class="st">"order"</span>, <span class="st">"mail"</span>, <span class="st">"receive"</span>, <span class="st">"will"</span>, <span class="st">"people"</span>, <span class="st">"report"</span>, </span>
<span id="cb24-6"><a href="#cb24-6" aria-hidden="true" tabindex="-1"></a><span class="st">"addresses"</span>, <span class="st">"free"</span>, <span class="st">"business"</span>, <span class="st">"email"</span>, <span class="st">"you"</span>, <span class="st">"credit"</span>, <span class="st">"your"</span>, </span>
<span id="cb24-7"><a href="#cb24-7" aria-hidden="true" tabindex="-1"></a><span class="st">"font"</span>, <span class="st">"n000"</span>, <span class="st">"money"</span>, <span class="st">"hp"</span>, <span class="st">"hpl"</span>, <span class="st">"george"</span>, <span class="st">"n650"</span>, <span class="st">"lab"</span>, </span>
<span id="cb24-8"><a href="#cb24-8" aria-hidden="true" tabindex="-1"></a><span class="st">"labs"</span>, <span class="st">"telnet"</span>, <span class="st">"n857"</span>, <span class="st">"data"</span>, <span class="st">"n415"</span>, <span class="st">"n85"</span>, <span class="st">"technology"</span>, </span>
<span id="cb24-9"><a href="#cb24-9" aria-hidden="true" tabindex="-1"></a><span class="st">"n1999"</span>, <span class="st">"parts"</span>, <span class="st">"pm"</span>, <span class="st">"direct"</span>, <span class="st">"cs"</span>, <span class="st">"meeting"</span>, <span class="st">"original"</span>, </span>
<span id="cb24-10"><a href="#cb24-10" aria-hidden="true" tabindex="-1"></a><span class="st">"project"</span>, <span class="st">"re"</span>, <span class="st">"edu"</span>, <span class="st">"table"</span>, <span class="st">"conference"</span>, <span class="st">"semicolon"</span>, <span class="st">"leftparen"</span>, </span>
<span id="cb24-11"><a href="#cb24-11" aria-hidden="true" tabindex="-1"></a><span class="st">"leftbrack"</span>, <span class="st">"bang"</span>, <span class="st">"dollar"</span>, <span class="st">"hash"</span>, <span class="st">"crl.av"</span>, <span class="st">"crl.long"</span>, </span>
<span id="cb24-12"><a href="#cb24-12" aria-hidden="true" tabindex="-1"></a><span class="st">"crl.tot"</span>, <span class="st">"yesno"</span>)</span>
<span id="cb24-13"><a href="#cb24-13" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(spambase) <span class="ot">&lt;-</span> nam</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Now load <em>rpart</em> and proceed with the calculations.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">21</span>)</span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>spam.rpart <span class="ot">&lt;-</span> <span class="fu">rpart</span>(yesno<span class="sc">~</span>., <span class="at">data=</span>spambase, <span class="at">cp=</span><span class="fl">0.0001</span>, <span class="at">method=</span><span class="st">"class"</span>)</span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a><span class="fu">printcp</span>(spam.rpart)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Classification tree:
rpart(formula = yesno ~ ., data = spambase, method = "class", 
    cp = 1e-04)

Variables actually used in tree construction:
 [1] address    addresses  all        bang       business   conference
 [7] credit     crl.av     crl.long   crl.tot    cs         direct    
[13] dollar     edu        email      font       free       george    
[19] hash       hp         hpl        internet   lab        labs      
[25] leftbrack  leftparen  mail       make       money      n1999     
[31] n415       n650       n857       order      original   over      
[37] parts      people     pm         receive    remove     report    
[43] table      threeD     will       you        your      

Root node error: 4486/4601 = 0.97501

n= 4601 

           CP nsplit rel error  xerror      xstd
1  0.00587011      0   1.00000 1.00000 0.0023604
2  0.00222916      3   0.98239 0.98373 0.0029934
3  0.00217343      4   0.98016 0.98417 0.0029781
4  0.00200624      9   0.96879 0.98417 0.0029781
5  0.00156041     11   0.96478 0.97994 0.0031198
6  0.00133749     15   0.95854 0.97303 0.0033355
7  0.00118888     16   0.95720 0.96991 0.0034275
8  0.00111458     20   0.95230 0.96634 0.0035290
9  0.00104027     29   0.94226 0.96589 0.0035414
10 0.00100312     32   0.93914 0.96567 0.0035476
11 0.00094739     34   0.93714 0.96322 0.0036148
12 0.00089166     38   0.93335 0.96099 0.0036745
13 0.00085451     42   0.92978 0.96010 0.0036981
14 0.00080250     48   0.92465 0.95854 0.0037388
15 0.00078021     53   0.92064 0.95698 0.0037789
16 0.00075791     55   0.91908 0.95586 0.0038073
17 0.00074305     69   0.90816 0.95586 0.0038073
18 0.00066875     85   0.89523 0.95074 0.0039341
19 0.00059444    110   0.87829 0.94739 0.0040139
20 0.00057958    114   0.87584 0.94516 0.0040658
21 0.00055729    119   0.87294 0.94583 0.0040504
22 0.00052014    127   0.86848 0.94583 0.0040504
23 0.00044583    130   0.86692 0.93914 0.0042017
24 0.00039010    193   0.83794 0.93981 0.0041869
25 0.00037153    197   0.83638 0.93981 0.0041869
26 0.00035667    209   0.83148 0.93981 0.0041869
27 0.00033437    214   0.82969 0.93981 0.0041869
28 0.00027864    218   0.82835 0.93959 0.0041919
29 0.00022292    226   0.82613 0.93959 0.0041919
30 0.00011146    241   0.82278 0.93781 0.0042311
31 0.00010000    243   0.82256 0.93803 0.0042262</code></pre>
</div>
</div>
<p>Figure @ref(spam) shows the plot of cross-validated relative error versus <code>cp</code>, for the full <code>spam</code> data set. For making a decision on the size of tree however, it is convenient to work from the information given by the function <code>printcp()</code>.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plotcp</span>(spam.rpart)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="ch8_files/figure-html/spam-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:50.0%"></p>
</figure>
</div>
</div>
</div>
<p>Setting <code>cp=0.0001</code> ensures, when the random number seed is set to 21, that the cross-validated relative error reaches a minimum, of 0.1958, at <code>nsplit=43</code>. Pruning to get the tree that is likely to have best predictive power can use <code>cp=0.001</code>. Adding the SE to the minimum cross-validated relative error gives 0.2. The smallest tree with an SE smaller than this is at <code>nsplit=36</code>; setting <code>cp=0.0012</code> will give this tree.</p>
<p>Here then are the two prunings:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>spam.rpart1 <span class="ot">&lt;-</span> <span class="fu">prune</span>(spam.rpart, <span class="at">cp=</span><span class="fl">0.001</span>)  <span class="co"># Minimum predicted error</span></span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>spam.rpart2 <span class="ot">&lt;-</span> <span class="fu">prune</span>(spam.rpart, <span class="at">cp=</span><span class="fl">0.0012</span>) <span class="co"># 1 SE pruning</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>



</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation column-page-right">
  <div class="nav-page nav-page-previous">
      <a 7="" href="./ch7.html" class="pagination-link  aria-label=" &lt;span="" to="" selected="" chapter="" exercises&lt;="" span&gt;"="">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Answers to Selected Chapter 7 Exercises</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./ch9.html" class="pagination-link" aria-label="<span class='chapter-number'>9</span>&nbsp; <span class='chapter-title'>Answers to Selected Chapter 9 Exercises</span>">
        <span class="nav-page-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Answers to Selected Chapter 9 Exercises</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>